@port = 3000
@host = http://localhost:{{port}}

#################### CATEGORIES #####################

GET {{host}}/api/categories

###
POST {{host}}/api/categories/new

###
PUT {{host}}/api/categories/update/:categoryId

###
DELETE {{host}}/api/categories/:categoryId


#################### COMMENTS #####################

GET {{host}}/api/comments

###
POST {{host}}/api/comments/new

###
PUT {{host}}/api/comments/update/:commentId

###
DELETE {{host}}/api/comments/:commentId

#################### FAVORITES #####################

GET {{host}}/api/favorites

###
POST {{host}}/api/favorites/new

###
PUT {{host}}/api/favorites/update/:favoriteId

###
DELETE {{host}}/api/favorites/:favoriteId

#################### ORDERS #####################

GET {{host}}/api/orders

###
POST {{host}}/api/orders/new

###
PUT {{host}}/api/orders/update/:orderId

###
DELETE {{host}}/api/orders/:orderId

#################### PRODUCTS #####################

GET {{host}}/api/products

###
POST {{host}}/api/products/new

###
PUT {{host}}/api/products/update/:productId

###
DELETE {{host}}/api/products/:productId

