@port = 3000
@host = http://localhost:{{port}}


#################### COMMENTS #####################

GET {{host}}/api/comments


### 1 azul,  4 beige
POST {{host}}/api/comments/new
Content-Type: application/json

{
    "text": "Me gustan los colores vibrantes", 
    "users_id": "6", 
    "products_id": "7"
}

###
PUT {{host}}/api/comments/update/6
Content-Type: application/json

{
    "text": "Es que me encanta este tono de azul", 
    "users_id": "2", 
    "products_id": "9"
}

###
DELETE {{host}}/api/comments/6
