@port = 3000
@host = http://localhost:{{port}}


#################### CATEGORIES #####################


GET {{host}}/api/categories

###
POST {{host}}/api/categories/new
Content-Type: application/json

{
    "title": "baño"
}

###
PUT {{host}}/api/categories/update/3
Content-Type: application/json

{
    "title": "mejunje"
}

###
DELETE {{host}}/api/categories/8

