@port = 3000
@host = http://localhost:{{port}}


#################### FAVORITES #####################

GET {{host}}/api/favorites

###
GET {{host}}/api/favorites/5

###
GET {{host}}/api/favorites/5/paginated?page=1&limit=16


###
POST {{host}}/api/favorites/new
Content-Type: application/json

{
    "users_id": "5", 
    "products_id": "7"
}

###
PUT {{host}}/api/favorites/update/7
Content-Type: application/json

{
    "users_id": "5", 
    "products_id": "4"
}

###
DELETE {{host}}/api/favorites/8
