@port = 3000
@host = http://localhost:{{port}}



#################### PRODUCTS #####################

GET {{host}}/api/products
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTMzNDcwNzd9.sxXMneMrsoF3bkezDcRCjtW3Hd-yrJXqzyIiAVhlBBg
###
GET {{host}}/api/products/1

###
GET {{host}}/api/products/paginated?page=1&limit=16

###
GET {{host}}/api/products/paginated?page=1&limit=16

###
GET {{host}}/api/products/category/4


###
POST {{host}}/api/products/new
Content-Type: application/json

{
    "title": "Gorra amarilla", 
    "description": "Gorra naranja de algodón", 
    "price": "37.90", 
    "image": "http://ecommerce.com/5932659.jpg", 
    "featured": "0", 
    "categories_id": "4"
}


###
PUT {{host}}/api/products/update/4
Content-Type: application/json

{
    "title": "Gorra gris", 
    "description": "Gorra gris de algodón", 
    "price": "37.90", 
    "image": "http://ecommerce.com/5932659.jpg", 
    "featured": "0", 
    "categories_id": "4"
}


###
DELETE {{host}}/api/products/4


